language: shell
sudo: required

env:
  global:
    - SHFMT_URL=https://github.com/mvdan/sh/releases/download/v0.4.0/shfmt_v0.4.0_linux_amd64

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

script:
  - curl -sSL $SHFMT_URL -o ~/shfmt
  - chmod +x ~/shfmt
  - ~/shfmt -l -w -i 2 .
  - git diff --exit-code && echo "shfmt OK"
  - shellcheck -V
  - shellcheck -e SC2021,SC2126,SC2034 **/*.sh && echo "shellcheck OK"
  - cd ..
  - git clone https://github.com/Neilpang/acmetest.git && cp -r acme.sh acmetest/ && cd acmetest
  - sudo ./letest.sh


matrix:
  fast_finish: true
  
  
