language: shell

env:
  global:
    - SHFMT_URL=https://github.com/mvdan/sh/releases/download/v0.4.0/shfmt_v0.4.0_linux_amd64

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

script:
  - curl -sSL $SHFMT_URL -o ~/shfmt
  - chmod +x ~/shfmt
  - shellcheck -V
  - shellcheck -e SC2021,SC2126,SC2034 **/*.sh && echo "shellcheck OK"
  - ~/shfmt -l -w -i 2 . && echo "shfmt OK" || git diff --exit-code || (echo "Run shfmt to fix the formatting issues" && false)
  - cd ..
  - curl -sSL https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok-stable-linux-amd64.zip && unzip ngrok-stable-linux-amd64.zip && export NGROK_BIN="$(pwd)/ngrok"
  - $NGROK_BIN
  - $NGROK_BIN http 80 --log stdout --log-format logfmt --log-level debug
  - git clone https://github.com/Neilpang/acmetest.git && cp -r acme.sh acmetest/ && cd acmetest && ./letest.sh


matrix:
  fast_finish: true
  
  
