
name: Build DockerHub
on:
  push:
    branches:
      - master
      - dev
    tags:
      - '*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: login to docker hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build and push the image
        run: |
          DOCKER_IMAGE=neilpang/acme.sh

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            BRANCH_TAG=${GITHUB_REF#refs/tags/}
            AUTO_UPGRADE=1
          fi

          if [[ $GITHUB_REF == refs/heads/* ]]; then
            BRANCH_TAG=${GITHUB_REF#refs/heads/}

            if [[ $BRANCH_TAG == master ]]; then
              BRANCH_TAG=latest
              AUTO_UPGRADE=1
            fi
          fi

          docker buildx build \
            --tag ${DOCKER_IMAGE}:${BRANCH_TAG} \
            --tag ${DOCKER_IMAGE}:${GITHUB_SHA} \
            --output "type=image,push=true" \
            --build-arg AUTO_UPGRADE=${AUTO_UPGRADE} \
            --platform linux/arm64/v8,linux/amd64,linux/arm/v6,linux/arm/v7,linux/386 .
